-- =====================================================
-- FIX: "Failed to delete selected users: Database error deleting user"
-- Run this in: Supabase Dashboard → SQL Editor
-- This script dynamically finds and drops ANY foreign keys on our public tables
-- and replaces them with correct, clean ON DELETE CASCADE or ON DELETE SET NULL rules.
-- This ensures deleting a user from auth.users works flawlessly and cleans up all data.
-- =====================================================

DO $$
DECLARE
    r RECORD;
BEGIN
    -- 1. Find and drop all existing foreign key constraints on the tables
    -- (This avoids failures from mismatched or autogenerated constraint names)
    FOR r IN (
        SELECT 
            tc.table_name, 
            tc.constraint_name
        FROM 
            information_schema.table_constraints AS tc 
            JOIN information_schema.key_column_usage AS kcu
              ON tc.constraint_name = kcu.constraint_name
              AND tc.table_schema = kcu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY' 
          AND tc.table_schema = 'public'
          AND tc.table_name IN ('profiles', 'workspaces', 'workspace_members', 'tasks', 'invitations')
    ) LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(r.table_name) || ' DROP CONSTRAINT IF EXISTS ' || quote_ident(r.constraint_name) || ' CASCADE;';
    END LOOP;
END $$;

-- 2. Add clean, named constraints with correct CASCADE / SET NULL rules
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey 
  FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.workspaces ADD CONSTRAINT workspaces_owner_id_fkey 
  FOREIGN KEY (owner_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.workspace_members ADD CONSTRAINT workspace_members_workspace_id_fkey 
  FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;

ALTER TABLE public.workspace_members ADD CONSTRAINT workspace_members_user_id_fkey 
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.workspace_members ADD CONSTRAINT workspace_members_invited_by_fkey 
  FOREIGN KEY (invited_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.tasks ADD CONSTRAINT tasks_workspace_id_fkey 
  FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;

ALTER TABLE public.tasks ADD CONSTRAINT tasks_assigned_to_fkey 
  FOREIGN KEY (assigned_to) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.tasks ADD CONSTRAINT tasks_created_by_fkey 
  FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.invitations ADD CONSTRAINT invitations_workspace_id_fkey 
  FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;
